###############
# File Access #
###############

[FileAccess]
default_permissions = "FILE"

[DirAccess]
default_permissions = "FILE"

[X509Certificate]
default_permissions = "FILE"

########
# HTTP #
########

[HTTPClient]
default_permissions = "HTTP"

[HTTPRequest]
default_permissions = "HTTP"

[TCPServer]
default_permissions = "HTTP"

[UDPServer]
default_permissions = "HTTP"

######
# OS #
######

[OS]
default_permissions = "OS"

###################
# Script Security #
###################

[Script]
default_permissions = "INTERNAL"

[ScriptExtension]
default_permissions = "INTERNAL"

################################################################################

[Engine]

[Engine.methods.GetAuthorInfo]
permissions = "BASE"

[Engine.methods.GetCopyrightInfo]
permissions = "BASE"

[Engine.methods.GetDonorInfo]
permissions = "BASE"

[Engine.methods.GetFramesDrawn]
permissions = "BASE"

[Engine.methods.GetFramesPerSecond]
permissions = "BASE"

[Engine.methods.GetLicenseInfo]
permissions = "BASE"

[Engine.methods.GetLicenseText]
permissions = "BASE"

[Engine.methods.GetMainLoop]
permissions = "BASE"

[Engine.methods.GetMaxFps]
permissions = "BASE"

[Engine.methods.GetMaxPhysicsStepsPerFrame]
permissions = "BASE"

[Engine.methods.GetPhysicsFrames]
permissions = "BASE"

[Engine.methods.GetPhysicsInterpolationFraction]
permissions = "BASE"

[Engine.methods.GetPhysicsJitterFix]
permissions = "BASE"

[Engine.methods.GetPhysicsTicksPerSecond]
permissions = "BASE"

[Engine.methods.GetProcessFrames]
permissions = "BASE"

[Engine.methods.GetScriptLanguage]
permissions = "BASE"

[Engine.methods.GetScriptLanguageCount]
permissions = "BASE"

[Engine.methods.GetSingleton]
permissions = "BASE"

[Engine.methods.GetSingletonList]
permissions = "BASE"

[Engine.methods.GetTimeScale]
permissions = "BASE"

[Engine.methods.GetVersionInfo]
permissions = "BASE"

[Engine.methods.HasSingleton]
permissions = "BASE"

[Engine.methods.IsEditorHint]
permissions = "BASE"

[Engine.methods.IsInPhysicsFrame]
permissions = "BASE"

################

[Input]
default_permissions = "BASE"

################

[Object]

[Object.methods.AddUserSignal]
permissions = "BASE"

[Object.methods.CanTranslateMessages]
permissions = "BASE"

[Object.methods.Connect]
permissions = "BASE"

[Object.methods.Disconnect]
permissions = "BASE"

[Object.methods.EmitSignal]
permissions = "BASE"

[Object.methods.GetClass]
permissions = "BASE"

[Object.methods.GetInstanceId]
permissions = "BASE"

[Object.methods.GetMeta]
permissions = "BASE"

[Object.methods.GetMetaList]
permissions = "BASE"

[Object.methods.GetMethodArgumentCount]
permissions = "BASE"

[Object.methods.GetMethodList]
permissions = "BASE"

[Object.methods.GetPropertyList]
permissions = "BASE"

[Object.methods.GetSignalList]
permissions = "BASE"

[Object.methods.HasMeta]
permissions = "BASE"

[Object.methods.HasMethod]
permissions = "BASE"

[Object.methods.HasSignal]
permissions = "BASE"

[Object.methods.HasUserSignal]
permissions = "BASE"

[Object.methods.IsBlockingSignals]
permissions = "BASE"

[Object.methods.IsConnected]
permissions = "BASE"

[Object.methods.IsQueuedForDeletion]
permissions = "BASE"

[Object.methods.RemoveMeta]
permissions = "BASE"

[Object.methods.RemoveUserSignal]
permissions = "BASE"

[Object.methods.SetBlockSignals]
permissions = "BASE"

[Object.methods.SetMessageTranslation]
permissions = "BASE"

[Object.methods.SetMeta]
permissions = "BASE"

[Object.methods.ToString]
permissions = "BASE"

[Object.methods.Tr]
permissions = "BASE"

[Object.methods.TrN]
permissions = "BASE"

################

[PhysicsDirectBodyState2D]
default_permissions = "BASE"

################

[PhysicsDirectBodyState3D]
default_permissions = "BASE"

################

[PhysicsDirectSpaceState2D]
default_permissions = "BASE"

################

[PhysicsDirectSpaceState3D]
default_permissions = "BASE"

################

[PhysicsServer2D]
default_permissions = "BASE"

################

[PhysicsServer3D]
default_permissions = "BASE"

################

[ProjectSettings]

[ProjectSettings.methods.GetSetting]
permissions = "BASE"

[ProjectSettings.methods.GetSettingWithOverride]
permissions = "BASE"

[ProjectSettings.methods.HasSetting]
permissions = "BASE"

################

[ResourceLoader]

[ResourceLoader.methods.GetRecognizedExtensionsForType]
permissions = "BASE"

################

[ResourceSaver]

[ResourceSaver.methods.GetRecognizedExtensions]
permissions = "BASE"

################

[SceneTree]

[SceneTree.methods.CreateTimer]
permissions = "BASE"

[SceneTree.methods.CreateTween]
permissions = "BASE"

[SceneTree.methods.GetCurrentScene]
permissions = "BASE"

[SceneTree.methods.GetEditedSceneRoot]
permissions = "BASE"

[SceneTree.methods.GetFirstNodeInGroup]
permissions = "BASE"

[SceneTree.methods.GetFrame]
permissions = "BASE"

[SceneTree.methods.GetMultiplayer]
permissions = "BASE"

[SceneTree.methods.GetNodeCount]
permissions = "BASE"

[SceneTree.methods.GetNodeCountInGroup]
permissions = "BASE"

[SceneTree.methods.GetNodesInGroup]
permissions = "BASE"

[SceneTree.methods.GetRoot]
permissions = "BASE"

[SceneTree.methods.HasGroup]
permissions = "BASE"

[SceneTree.methods.IsPaused]
permissions = "BASE"

[SceneTree.methods.IsPhysicsInterpolationEnabled]
permissions = "BASE"

[SceneTree.methods.IsQuitOnGoBack]
permissions = "BASE"

################

[Thread]
default_permissions = "INTERNAL"

################

[Time]

[Time.methods.GetTicksMsec]
permissions = "BASE"

[Time.methods.GetTicksUsec]
permissions = "BASE"

################
