indent = "    "
header_comment_msg = "This file is automatically generated. Do not edit!"
header_comment = "// " + header_comment_msg
header_comment_lua = "-- " + header_comment_msg
builtin_metatable_prefix = "Godot.Builtin."
class_metatable_prefix = "Godot.Object."

typed_array_prefix = "typedarray::"
enum_prefix = "enum::"
bitfield_prefix = "bitfield::"
